services:
  backend:
    image: node:16
    working_dir: /app
    volumes:
      - ./services/backend:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=ima_crm
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=ima_crm_sk_2024
    mem_limit: 1024m
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: admin
      POSTGRES_DB: ima_crm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    mem_limit: 512m

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    mem_limit: 256m

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./services/frontend:/app:delegated
      - /app/node_modules
    ports:
      - "3002:3002"
    command: sh -c "export NODE_OPTIONS='--max-old-space-size=1536' && npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_NO_WARNINGS=1
      - NODE_OPTIONS=--max-old-space-size=1536
    mem_limit: 1536m
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    mem_limit: 256m
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
  redisdata: