services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./services/backend/.env.production
    mem_limit: 1024m
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: admin
      POSTGRES_DB: ima_crm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    mem_limit: 512m

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    mem_limit: 256m

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./services/frontend/.env.production
    mem_limit: 1536m
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    mem_limit: 256m
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
  redisdata: